### ISSUE TITLE
extraction.py (line 28): AttributeError: 'dict' object has no attribute 'iteritems' in python 3

### ISSUE THREAD

**Issue by RomainBrunias** [monkeylearn/monkeylearn-python#12]
```
File "extraction.py", line 28, in extract
    for key, value in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

A similar issue is raised in http://stackoverflow.com/a/30418498/2952688
**iteritems()** being deprecated in python 3, **items()** has to be used instead.

Commit https://github.com/monkeylearn/monkeylearn-python/commit/f3eee368e13ee37048d52bde0d067efea057fef8 seems to be the culprit.

**Comment by rsteca** [comment]
Fixed
