### ISSUE TITLE
Calls to classify end point seem to use 1 API call per string not per list of strings

### ISSUE THREAD

**Issue by AWegnerGitHub** [monkeylearn/monkeylearn-python#9]
If I understand the "classify" API documentation correctly, I should be able to pass multiple text strings in a single call and only use 1 API call, correct? I'm basing this on

> This endpoint allows you to perform the classification of many text samples using only one request to a custom or public module.

Assuming my understanding is accurate, I am seeing different behavior. Instead of a single API call for a list of text strings, I see one API call per text string.

This is my sample code

```
from monkeylearn import MonkeyLearn
import user_settings

MONKEYLEARN_API_KEY = user_settings.KEY
MODULE_ID = user_settings.MODULE_ID

ml = MonkeyLearn(MONKEYLEARN_API_KEY)
res = ml.classifiers.detail(MODULE_ID)
samples = ['this is a string',
           'a dog barks on tuesday',
           'i like purple muffins',
           'apples are funny fruit',
           'the house is up a mountain',
           'cats do not like trees',
           'computers will take over',
           'you sank my battleship',
           'duck, duck, goose',
           'yellow baby buggy bumpers']

res = ml.classifiers.classify(MODULE_ID, samples, sandbox=True, debug=False)
print("Quota Remaining")
print("-"*20)
pprint.pprint(res.query_limit_remaining, indent=4)
```

Two runs, back to back, of this print the following:

> RUN 1:
> Quota Remaining
> \--------------------
> '99940'

---
> RUN 2:
> Quota Remaining
> \--------------------
> '99930'

Notice that the remaining quota is 10 apart between runs. This is the same number of sample text strings. If I comment out 5 of them and run it again, I get this output:

> Quota Remaining
> \--------------------
> '99915'

To me, this is confirming that I am using 1 API call to the classify endpoint per string, not per group of strings. 

Is this the expected behavior, or should my list of 10 strings only be costing 1 API call?

**Comment by rsteca** [comment]
Hi! This is the expected behaviour. Each classification costs 1 query. The difference between sending a list of texts instead of sending one text at a time is that less HTTP requests are performed in the former and the classification works way faster.

**Comment by AWegnerGitHub** [comment]
Thank you for the clarification.
